### ISSUE TITLE
Python3 Support?

### ISSUE THREAD

**Issue by mckinziebrandon** [google/sling#127]
I've been using this (amazing) project a lot lately, and one thing I'd love is support with Python3. I'm interested in implementing support for this. One thing that would be helpful for me to know is the list of what's needed to do so, if you'd be kind enough to provide it. 

From what I can tell, the list would include:
- The standard minor modifications to every python file such that they work with both 2.7 and 3+. 
- Modifying the [TensorFlow link](https://github.com/forgeAI/sling-private/blob/master/third_party/tensorflow/BUILD#L21) to point to a python3 version.

I'm assuming this list is likely much more extensive than just the two points above. Could you tell me the remaining steps needed to get support for python3? I'd of course be happy to submit a PR if I get a working implementation. Thanks!

**Comment by ringgaard** [comment]
I don't have much experience with Python 3, so I would not know what it would take to add Python 3 support to SLING. Since SLING is still in the experimental stage, we would like to stick to supporting only one version of each tool, so at the moment we are stuck with GCC 4, C++ 11, Python 2.7, and Linux. 

You could clone the repo and try to make a Python 3 version. If it is only minimal and non-intrusive changes that are needed, we can consider pulling these into the main SLING repo.

We are also using Python C extensions now (see pysling.so), so these also need to be Python 2 and 3 compatible.

**Comment by mckinziebrandon** [comment]
Sounds good. Thanks for the response!

**Comment by sw1sh** [comment]
@mckinziebrandon Any updates on this?

**Comment by mckinziebrandon** [comment]
Unfortunately, no. I don't have the code anymore but I was able to make some parts work, but kept running into various issues and basically gave up.

**Comment by ringgaard** [comment]
Looks like we are going to look into Python 3 support in 2019Q2, so stay tuned...

**Comment by ringgaard** [comment]
PR #366 has now been checked in, so we now support Python 3. Since Python 2.7 will no longer be maintained after January 1, 2020, including no security updates, we will not support Python 2.7 going forward.

**Comment by johndpope** [comment]
New Mac OS - 10.15 is updating to python 3.
