### ISSUE TITLE
verbal/nominal coordination and negation

### ISSUE THREAD

**Issue by jackxpeng** [google/sling#197]
Should another level of frame be added to handle things like "John and Mary" and "book club except John"?  I tried "I called John and Mary" and it only connected call to John. Mary is not connected at all. I wonder what the correct frame semantic would look like. Say you do add another layer to encapsulate these, what type of frame would it be? persons for "John and Mary"? organization for "book club except John"?

If I do go this route, would sling's transition system be able to generate nested frames like this? Thanks.

**Comment by ringgaard** [comment]
The "John and Mary" problem is probably due to issues with our internal pipeline for converting OntoNotes to the training data we use for training the parser. Although the OntoNotes corpus has constituency trees, we convert these to dependency parse trees, and we therefore loose the correct coordination bracketing.

The frame annotations we generate from OntoNotes are by no means perfect, and only cover some linguistic phenomenon. [AMR](https://amr.isi.edu/) allows for a more precise annotations of some of the issues, but ignores other aspects like number and tense... no annotations are "perfect".

While the training data for SEMPAR does not have any nested mentions, the SLING parser transition systems supports nested frames as long as there are no crossing mention boundaries. If you make training data with nested mentions, it should in theory work, although we have not extensively tested this. If you find any bugs, we are happy to fix them.
