### ISSUE TITLE
Check failed: index != -1(-1 vs. -1)

### ISSUE THREAD

**Issue by satya-323** [google/sling#200]
Hi,

I would like to enquire about this error which I get when I try to train the model.

Here's the error:
`INFO:tensorflow:Initial cost at step 0: 1.590217
[2018-06-19 19:35:10.392470: F sling/nlp/parser/trainer/transition-state.cc:83] Check failed: index != -1 (-1 vs. -1)REFER:len=23:0
./sling/nlp/parser/tools/train.sh: line 242: 20447 Aborted                 (core dumped) python sling/nlp/parser/tools/train.py --master_spec="${OUTPUT_FOLDER}/master_spec" --hyperparams="${HYPERPARAMS}" --output_folder=${OUTPUT_FOLDER} --flow=${OUTPUT_FOLDER}/sempar.flow --commons=${COMMONS} --train_corpus=${TRAIN_FILEPATTERN} --dev_corpus=${DEV_FILEPATTERN} --batch_size=${BATCH_SIZE} --report_every=${REPORT_EVERY} --train_steps=${TRAIN_STEPS} --logtostderr`

This seems to be similar to #157 . I don't get what type of similarity are we talking about in that issue.

**Comment by rahul1980** [comment]
Is possible to isolate the document that contains this action and share it (along with the commons store and action table) ?
The action table should be generated in $OUTPUT_FOLDER/table.
Like #157, the crash happens when one of the golden actions in a training document is not in the table (this shouldn't happen).
I am not sure what fix the authors in #157 applied to their corpus, but the crash went away with the fix.

I'll be happy to help if I can see the document/store.

**Comment by satya-323** [comment]
Hi again,

I have attached below the document which gives this error and also the commons store and action table. I am working on GENIA dataset.

[files.zip](https://github.com/google/sling/files/2118026/files.zip)

**Comment by rahul1980** [comment]
Hi,
   I checked the document and the action table and found that:
a) The document didn't contain any mention of length 23 (which would have led it to output a REFER:len=23:0 action as in your crash).

b)  I did however notice another potential problem: all the mentions seem to evoke the identical protein frame. It seems to me that this is not what you intend, e.g. "cytokines" and "IL-2" should evoke two different frames of type protein, but right now evoke the same frame. This also explains the erroneous presence of REFER actions in your data instead of EVOKE actions. Note that REFER action is primarily meant to capture pronouns. E.g. in "John gave Mary his word", John and Mary evoke different frames of type Person, and "his" evokes the same frame as John.

c) The action table seems to have max_refer_target = -1. This could be a bug on our part. If your corpus train corpus can be shared, I can hunt this down. The REFER action is not rigorously tested so a bug is very much possible.

Meanwhile, do you want to fix (b) in all documents and give it another try?

**Comment by satya-323** [comment]
Hi,
Thanks for the help till now.
I would like to fix the problem (b) first and try again but there is a problem, I am adding mentions using a loop which iterates over certain phrases and then adds the entity evoked by them using add_mention(). So it is automatically adding the reference to it instead of evoking a new frame. Is there a way to avoid doing that?

**Comment by rahul1980** [comment]
Something like this should work (assuming you are using python to create documents):

store = ...   # document's store
mention1 = document.add_mention(start1, end1)
frame1 = store.parse(data="{isa: /entity/Proteins}")
mention1.evoke(frame1)

mention2 = document.add_mention(start2, end2)
frame2 = store.parse(data="{isa: /entity/Proteins}")   # another frame
mention2.evoke(frame2)

**Comment by satya-323** [comment]
Hi,
I tried the above fix and now I am able to train the model without any errors.
Thank you so much for the help.
