### ISSUE TITLE
Request: Checkpoint restart training

### ISSUE THREAD

**Issue by SasCezar** [google/sling#333]
I was wondering if it was possible to get the possibility to restart the training processes from a previously saved checkpoint.

**Comment by rahul1980** [comment]
It is definitely possible --- however it is somewhat messy. We would need to pickle all the parameters and the optimizer and PRNG states and save them (e.g. via torch.save()) into another file and then restore them on resumption. However we already have a file (the flow file), so it feels weird to have a second file that mostly mirrors the contents of the flow file, but which will only serve torch.load(). 

On the other hand, resuming training from the flow file is not straightforward -- first, it doesn't store the pickled form of the parameters, and second it doesn't save the optimizer & PRNG state.

Due to this we haven't really worked on this. May I ask, is resuming training a pressing use case for you? For the Ontonotes corpus, it takes <18 hours to train a reasonable model, so resuming training would not be of big help there.

**Comment by SasCezar** [comment]
Thanks, now that you pointed out, duplicating stuff just for 18h of training is not worth.

I'm using larger embeddings, so the time for each batch of size 8 is around 2.5 sec on a cluster. This brings me to train models for 4 days, and for unknown reasons sometimes the training stops during the dev evaluation. It just prints:
```
Annotating dev documents [2019-02-17 18:53:01.492149] (rss=183928)
Annotated 100 documents [2019-02-17 18:53:16.498858] (rss=183928)
Annotated 200 documents [2019-02-17 18:53:29.914048] (rss=183928)
Annotated 300 documents [2019-02-17 18:53:42.750969] (rss=183928)
Done. Log is available at /path_to_log/log.
```

I'will try to set up an example where the training stops and open an issue with more information. For now, I only know that this happens on specific files (not Ontonotes), but I'm not sure if the training file affects this behaviour or not.

**Comment by cklckl** [comment]
I have some question about the training speed. I tried the same training data on older version SLING (v1.1.0) and it's about 8x ~ 10x faster. Is it caused by some setting or any different model setting?

**Comment by rahul1980** [comment]
v1.1.0 used Syntaxnet over Tensorflow for training. Syntaxnet was implemented in C++ and had batching so it was faster. We moved to a pure python trainer (unbatched) over PyTorch because Syntaxnet wasn't extensible to the cascaded architecture that we eventually implemented. While this does slow down training, we are looking at ways to re-introduce batching in the cascaded architecture and make a few more optimizations. Please stay tuned.
