### ISSUE TITLE
The caspar.flow appears to be un-trained 

### ISSUE THREAD

**Issue by lenyabloko** [google/sling#403]
I just tested the parser with caspar.flow and this is what I got

python3 test.py
text: John Loves Mary
{=#1 
  :document
  text: "John Loves Mary"
  tokens: [{=#2 
    start: 0
    size: 4
  }, {=#3 
    start: 5
    size: 5
  }, {=#4 
    start: 11
    size: 4
  }]
  mention: {=#5 
    begin: 0
    evokes: {=#6 
      :thing
    }
  }
  mention: {=#7 
    begin: 1
    evokes: {=#8 
      :/pb/predicate
      /pb/ARG0: #6
      /pb/ARG1: {=#9 
        :thing
      }
    }
  }
  mention: {=#10 
    begin: 2
    evokes: #9
  }
}
mention John
mention Loves
mention Mary

**Comment by ringgaard** [comment]
At a glance, it looks ok to me. The caspar model has been trained purely on OntoNotes, which does not have very good entity type data.

**Comment by lenyabloko** [comment]
In the training section if help pages https://github.com/google/sling/blob/master/doc/guide/training.md
It lists the same example. So I assumed that example would work. Is this a part of Ontonotes corpus? If not, can you give a good example of working parse

**Comment by ringgaard** [comment]
The new OntoNotes conversion is different from the example we give in the documentation. We should get this updated. There are a couple of differences:

* To make it more comparable with SRL systems we no longer predict the predicate sense and just mark the predicate with /pb/predicate.
* The entity types we get from OntoNotes are very poor compared to the Google-internal conversion we started out using, e.g. many first name mentions like "Peter" and "Mary" are tagged as "thing" because the "New Testament" section of the OntoNotes training data does not have an entity type annotations.

We are working on a better system that is using Wikipedia for training data, but this is not quite ready yet.

**Comment by lenyabloko** [comment]
Thank you for update. What is the best way to be posted on new developments?

**Comment by ringgaard** [comment]
All the new stuff goes through pull requests, so this would be the best source of information. Since this is a research project, we do not have releases with version numbers and release statements.

**Comment by krasi0** [comment]
@ringgaard Has there been any progress on using Wikipedia for training data?

**Comment by ringgaard** [comment]
We are not quite ready with the parser trained on silver data from Wikipedia. You can take a look at my dev branch If you want to follow the progress: https://github.com/ringgaard/sling/tree/dev

You can take a look at [train_knolex.py]( https://github.com/ringgaard/sling/blob/dev/sling/nlp/parser/tools/train_knolex.py) to see how to run the parser trainer. Please notice that this is work-in-progress, and the dev branch is not always in a functional state.

**Comment by krasi0** [comment]
@ringgaard Wow, I hadn't suspected that there is so much activity going on in your fork. Thanks for the heads up!

Kinda unrelated, but I make extensive use of the frame related C++ classes in `https://github.com/google/sling/tree/master/sling`. Would you recommend that I switch to your branch at `https://github.com/ringgaard/sling/tree/dev/sling` instead? I am asking because I can see that there has been a lot of fixes and improvements as compared to `google:master`?

**Comment by ringgaard** [comment]
@krasi0 You are welcome to try out my dev branch if you want to be on the bleeding edge. I think almost all the changes to sling/frames are in the master branch by now, but there are a bunch of stuff related to sling/nlp/parsing and related stuff that I still need to complete and get in shape to be submitted to google/master.
